# Generated by Django 4.1 on 2024-04-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='public',
            field=models.CharField(choices=[('PRIVATE', 'False'), ('PUBLIC', 'True')], default='PRIVATE', max_length=8),
        ),
    ]
